#!/bin/bash
echo "$VH_ROOT"
echo $(ls $VH_ROOT)
cd "$VH_ROOT/front"
npm install
npm run build
cd ..
cd "$VH_ROOT/back"
npm install
cd ..
cd "$VH_ROOT/back/src/python"
python3 -m venv env
source env/bin/activate
python3 -m pip install -r requirements.txt