#!/bin/bash
VH_ROOT=$(scripts/get-root)
cd $VH_ROOT
rm -rf docker/build || true
mkdir -p docker/build
mkdir -p docker/build/back
mkdir -p docker/build/front
cp -a ./back/* docker/build/back
cp -a ./front/* docker/build/front
cp docker/prepare-docker docker/build/prepare-docker
