#!/bin/bash
echo "$(whoami)"
[ "$UID" -eq 0 ] || exec sudo "$0" "$@"
export VH_ROOT="$HOME/virtual-hendi"
sudo apt install -y nodejs npm python3 python3-venv
cd "$VH_ROOT/front"
npm install
cd "$VH_ROOT/back"
npm install
cd "$VH_ROOT/back/src/python"
python3 -m venv env
source env/bin/activate
python3 -m pip install -r requirements.txt
cd "$VH_ROOT"
