#!/bin/bash
set -euo pipefail
echo "uploading to s3..."
aws s3 cp dist/web s3://virtual-hendi/web --recursive --acl public-read
aws s3 cp dist/virtual-hendi s3://virtual-hendi/virtual-hendi --recursive --acl public-read
echo "deploying with terraform..."
export TF_VAR_VH_ROOT=$(scripts/get-root)
cd terraform
terraform init
terraform validate
terraform plan
terraform apply
