#!/bin/bash
export VH_ROOT="$HOME/virtual-hendi"
apt install -y nodejs npm nginx python3 python3-venv
cd "$VH_ROOT/front"
npm install
cd "$VH_ROOT/back"
npm install
cd "$VH_ROOT/back/src/python"
source env/bin/activate
python3 -m pip install -r requirements.txt
cd "$VH_ROOT"
cp scripts/default /etc/nginx/sites-enabled/default
cp scripts/virtual-hendi.service /etc/init.d/virtual-hendi.service
chmod +x /etc/init.d/virtual-hendi.service
update-rc.d virtual-hendi.service defaults
update-rc.d virtual-hendi.service enable
service nginx enable
service virtual-hendi.service enable