#!/bin/bash
sudo -i
apt update
apt install git
git clone https://github.com/isaac-j-miller/virtual-hendi
cd virtual-hendi
chmod +x scripts/*
scripts/prepare
service nginx start
service virtual-hendi start

