#!/bin/bash
set -euo pipefail
VH_ROOT=$(scripts/get-root)
scripts/rebuild-front
cd dev
VH_ROOT="$VH_ROOT" "./node_modules/.bin/nodemon" --config "${VH_ROOT}/nodemon.json" --watch "${VH_ROOT}/front" index.js 
