#!/bin/bash
set -euo pipefail
VH_ROOT=$(scripts/get-root)
cd "${VH_ROOT}/front"
npm run build
cd "$VH_ROOT"
VH_ROOT="$VH_ROOT" "./dev/node_modules/.bin/nodemon" --config "./nodemon.json" dev/index.js 
